---
# file: main.yml
- name: Create project {{ project_name }}
  oc:
    state: present
    inline:
      kind: ProjectRequest
      metadata:
        name: "{{ project_name }}"
      displayName: "{{ project_display_name }}"
      description: "{{ project_description }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
    apiport: "{{ apiport | default(8443) }}"
    apihost: "{{ apihost | default('localhost') }}"
- name: Create user {{ user_name }}
  oc:
    state: present
    inline:
      kind: User
      fullName: "{{ user_name }}"
      metadata:
        name: "{{ user_name }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
    apiport: "{{ apiport | default(8443) }}"
    apihost: "{{ apihost | default('localhost') }}"
- name: Add project role {{ project_role }} to user {{ user_name }}
  oc:
    state: present
    inline:
      kind: RoleBinding
      metadata:
        name: "{{ project_role }}"
        namespace: "{{ project_name }}"
      roleRef:
        name: "{{ project_role }}"
      userNames:
      - "{{ user_name }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
    apiport: "{{ apiport | default(8443) }}"
    apihost: "{{ apihost | default('localhost') }}"
- name: Set project quotas
  oc:
    state: present
    inline:
      kind: ResourceQuota
      metadata:
        name: ocp
        namespace: "{{ project_name }}"
      spec:
        hard:
          pods: "{{ pod_quota }}"
          services: "{{ service_quota }}"
          replicationcontrollers: "{{ rc_quota }}"
          secrets: "{{ secret_quota }}"
          requests.storage: "{{ storage_quota }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
    apiport: "{{ apiport | default(8443) }}"
    apihost: "{{ apihost | default('localhost') }}"

- name: Add Managed Label
  oc:
    state: present
    inline:
      kind: Namespace
      metadata:
        name: "{{ project_name }}"
        labels:
          ansible_managed: 'true'
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
    apiport: "{{ apiport | default(8443) }}"
    apihost: "{{ apihost | default('localhost') }}"
